basePath: /
host: localhost:8000
info:
  contact: {}
  description: API Server for TodoList Application
  title: Todo App API
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
